FROM war-detector:latest
USER root
RUN /app/.venv/bin/python -m ensurepip --upgrade && \
    /app/.venv/bin/python -m pip install --upgrade pip
RUN rm -rf /app/.venv/lib/python3.12/site-packages/opencv* && \
    /app/.venv/bin/python -m pip install --no-cache-dir opencv-python-headless==4.12.0.88
USER bentoml