"""initial

Revision ID: d937a735366c
Revises: 
Create Date: 2026-03-07 17:41:53.555738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd937a735366c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Detected_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('not_detected_minio_path', sa.String(), nullable=False),
    sa.Column('detected_minio_path', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='DetectionService'
    )
    op.create_table('Detected_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('box_x1', sa.Integer(), nullable=False),
    sa.Column('box_y1', sa.Integer(), nullable=False),
    sa.Column('box_x2', sa.Integer(), nullable=False),
    sa.Column('box_y2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['DetectionService.Detected_frames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='DetectionService'
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_table('Detected_objects', schema='DetectionService')
    op.drop_table('Detected_frames', schema='DetectionService')
    # ### end Alembic commands ###
