"""initial

Revision ID: a0609017da7f
Revises: 
Create Date: 2026-03-07 16:59:03.709708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0609017da7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('minio_path', sa.String(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='VideoProducerService'
    )
    op.create_table('frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('minio_path', sa.String(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='not_processed', nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['VideoProducerService.videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='VideoProducerService'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frames', schema='VideoProducerService')
    op.drop_table('videos', schema='VideoProducerService')
    # ### end Alembic commands ###
